spring:
  application:
    name: platform
  datasource:
    url: jdbc:postgresql://localhost:5432/testmgmt
    username: testmgmt
    password: testmgmt
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/testmgmt
management:
  endpoint:
    health:
      show-details: always
